### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'findAll'

### ISSUE THREAD

**Issue by geeklimit** [kevin91nl/cryptohist#3]
It seems like CoinMarketCap is returning fields that are empty, likely for zero-volume coins.

Should the command throwing the error be a 'try (to find this data) except if type is NoneType (use zero)?

Console:

```
Fetching KASHH... (892 / 897)
Fetching MGC... (893 / 897)
Fetching BITOK... (894 / 897)
Fetching FRCT... (895 / 897)
Traceback (most recent call last):
  File "coinmarketcap.py", line 192, in <module>
    fetcher.fetch_all()
  File "coinmarketcap.py", line 57, in fetch_all
    self.fetch_by_symbol(symbol)
  File "coinmarketcap.py", line 67, in fetch_by_symbol
    return self._fetch_data(self.df_symbol)
  File "coinmarketcap.py", line 97, in _fetch_data
    for thead in table.findAll('thead'):
AttributeError: 'NoneType' object has no attribute 'findAll'
```

**Comment by kevin91nl** [comment]
Hi,

Thank you for pointing this out. The script is now skipping coins on CoinMarketCap with non-existing tables since it does not contain any data.

**Comment by geeklimit** [comment]
👍
